### ISSUE TITLE
How to add/Delete/Update data

### ISSUE THREAD

**Issue by xiangzz159** [SUNCAT-Center/CatalysisHubBackend#38]
I found this example just select data

**Comment by kirstenwinther** [comment]
Hi @xiangzz159. You're right - our current implementation uses flask/sqlalchemy/graphql to select data only. If you wan't to see how the data is written to our database, take a look at my repository CatalysisHubCli. This is not using Flask/graphQL however, but raw SQL statements in python and a cli around that.
